spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    auth-exp: ${AUTH_CODE_EXP}

jwt:
  secret_key: ${SECRET_KEY}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}
  header: ${HEADER}
  prefix: ${PREFIX}


redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

socket:
  port: 8081
